export const CHANGE_STYLE_MODE = 'CHANGE_STYLE_MODE';
export const GET_INDEX_IMG = 'GET_INDEX_IMG';
export const TAG_LIST = 'TAG_LIST';
export const ARTICLE_LIST = 'ARTICLE_LIST';
export const ARTICLE_DETAIL = 'ARTICLE_DETAIL';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';

export const COMMENT_LIST = 'COMMENT_LIST';
export const PRENEXT_ARTICLE = 'PRENEXT_ARTICLE';
export const CHANGE_OPTIONS = 'CHANGE_OPTIONS';
export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST';
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST';


export const LOGOUT_USER = 'LOGOUT_USER'; //登录失败
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'; //登录成功
export const LOGIN_FAILURE = 'LOGIN_FAILURE'; //登录失败

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'; //注册成功
export const REGISTER_FAILURE = 'REGISTER_FAILURE'; //注册失败
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS';
export const USERINFO_FAILURE = 'USERINFO_FAILURE';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';


export const SUCCESS_ADD_COMMENT = 'SUCCESS_ADD_COMMENT';
export const FAILURE_ADD_COMMENT = 'FAILURE_ADD_COMMENT';
export const SUCCESS_ADD_REPLY = 'SUCCESS_ADD_REPLY';
export const FAILURE_ADD_REPLY = 'FAILURE_ADD_REPLY';

export const SUCCESS_GET_APPS = 'SUCCESS_GET_APPS';
export const FAILURE_GET_APPS = 'FAILURE_GET_APPS';

export const FAILURE_GET_SNSLOGINS = 'FAILURE_GET_SNSLOGINS';
export const SUCCESS_GET_SNSLOGINS = 'SUCCESS_GET_SNSLOGINS';

export const AUTH_ERRMSG_CLEAR = 'AUTH_ERRMSG_CLEAR'; //清空错误验证信息
export const AUTH_ERRMSG_UPDATE = 'AUTH_ERRMSG_UPDATE'; //更新错误验证信息